Backpack9:
  Enable: true
  Result: BAT_SPAWN_EGG
  Recipe:
    Slot0: LEATHER
    Slot1: LEATHER
    Slot2: LEATHER
    Slot3: LEATHER
    Slot4: CHEST
    Slot5: LEATHER
    Slot6: LEATHER
    Slot7: LEATHER
    Slot8: LEATHER
Backpack18:
  Enable: true
  Result: SKELETON_SPAWN_EGG
  Recipe:
    Slot0: IRON_INGOT
    Slot1: IRON_INGOT
    Slot2: IRON_INGOT
    Slot3: LEATHER
    Slot4: BACKPACK9 # ALLOWS FOR UPGRADING SMALLER BACKPACK
    Slot5: LEATHER
    Slot6: IRON_INGOT
    Slot7: IRON_INGOT
    Slot8: IRON_INGOT
Backpack27:
  Enable: true
  Result: COW_SPAWN_EGG
  Recipe:
    Slot0: GOLD_INGOT
    Slot1: GOLD_INGOT
    Slot2: GOLD_INGOT
    Slot3: LEATHER
    Slot4: BACKPACK18
    Slot5: LEATHER
    Slot6: GOLD_INGOT
    Slot7: GOLD_INGOT
    Slot8: GOLD_INGOT
Backpack36:
  Enable: true
  Result: CHICKEN_SPAWN_EGG
  Recipe:
    Slot0: IRON_BLOCK
    Slot1: IRON_BLOCK
    Slot2: IRON_BLOCK
    Slot3: LEATHER
    Slot4: BACKPACK27
    Slot5: LEATHER
    Slot6: IRON_BLOCK
    Slot7: IRON_BLOCK
    Slot8: IRON_BLOCK
Backpack45:
  Enable: true
  Result: ZOMBIE_SPAWN_EGG
  Recipe:
    Slot0: GOLD_BLOCK
    Slot1: GOLD_BLOCK
    Slot2: GOLD_BLOCK
    Slot3: LEATHER
    Slot4: BACKPACK36
    Slot5: LEATHER
    Slot6: GOLD_BLOCK
    Slot7: GOLD_BLOCK
    Slot8: GOLD_BLOCK
Backpack54:
  Enable: true
  Result: SPIDER_SPAWN_EGG
  Recipe:
    Slot0: DIAMOND
    Slot1: DIAMOND
    Slot2: DIAMOND
    Slot3: LEATHER
    Slot4: BACKPACK45
    Slot5: LEATHER
    Slot6: DIAMOND
    Slot7: DIAMOND
    Slot8: DIAMOND