# Material list: 'http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html'
# Item ID list: 'http://www.minecraftinfo.com/idlist.htm'
# Days-Before-Removal: 60                   # number of days before old unused backpacks are removed from database. Recommended for large servers.
# Backpack9:                                # The number represents the number of Slots the backpack has.
#   Enable: true                            # Enable or disable backpack
#   Material: MONSTER_EGG                   # Use the Material list above to find the correct values.
#   Durability: 50                          # Use the Item ID list above to find the correct values. ex. Spruce planks is 5:1, durability would be 1. default value for items with no durability is 0 
#   Recipe:                                 # Each line represents a row in the crafting table with three comma separated items representing Slots. If you want to make a Slot empty put EMPTY in that field.
#   - LEATHER,LEATHER,LEATHER
#   - WOOL:1,CHEST,WOOL:1                   # Here is an example of using Orange Wool, by adding the Material name followed by its durability value.
#   - LEATHER,LEATHER,LEATHER
#
Days-Before-Removal: 60

Backpack9:
  Enable: true
  Result: BAT_SPAWN_EGG
  Recipe:
    Slot0: LEATHER
    Slot1: LEATHER
    Slot2: LEATHER
    Slot3: LEATHER
    Slot4: CHEST
    Slot5: LEATHER
    Slot6: LEATHER
    Slot7: LEATHER
    Slot8: LEATHER
Backpack18:
  Enable: true
  Result: SKELETON_SPAWN_EGG
  Recipe:
    Slot0: IRON_INGOT
    Slot1: IRON_INGOT
    Slot2: IRON_INGOT
    Slot3: LEATHER
    Slot4: CHEST
    Slot5: LEATHER
    Slot6: IRON_INGOT
    Slot7: IRON_INGOT
    Slot8: IRON_INGOT
Backpack27:
  Enable: true
  Result: COW_SPAWN_EGG
  Recipe:
    Slot0: GOLD_INGOT
    Slot1: GOLD_INGOT
    Slot2: GOLD_INGOT
    Slot3: LEATHER
    Slot4: CHEST
    Slot5: LEATHER
    Slot6: GOLD_INGOT
    Slot7: GOLD_INGOT
    Slot8: GOLD_INGOT
Backpack36:
  Enable: true
  Result: CHICKEN_SPAWN_EGG
  Recipe:
    Slot0: IRON_BLOCK
    Slot1: IRON_BLOCK
    Slot2: IRON_BLOCK
    Slot3: LEATHER
    Slot4: CHEST
    Slot5: LEATHER
    Slot6: IRON_BLOCK
    Slot7: IRON_BLOCK
    Slot8: IRON_BLOCK
Backpack45:
  Enable: true
  Result: ZOMBIE_SPAWN_EGG
  Recipe:
    Slot0: GOLD_BLOCK
    Slot1: GOLD_BLOCK
    Slot2: GOLD_BLOCK
    Slot3: LEATHER
    Slot4: CHEST
    Slot5: LEATHER
    Slot6: GOLD_BLOCK
    Slot7: GOLD_BLOCK
    Slot8: GOLD_BLOCK
Backpack54:
  Enable: true
  Result: SPIDER_SPAWN_EGG
  Recipe:
    Slot0: DIAMOND
    Slot1: DIAMOND
    Slot2: DIAMOND
    Slot3: LEATHER
    Slot4: CHEST
    Slot5: LEATHER
    Slot6: DIAMOND
    Slot7: DIAMOND
    Slot8: DIAMOND