name: BetterBackpacks
main: org.trentech.betterbackpacks.BetterBackpacks
version: 2.0.0
api-version: 1.13
commands:
  backpack:
    description: Better Backpacks
    usage: </command>
    aliases: [bp]